### ISSUE TITLE
Some uri escape to %2520 instead of %20

### ISSUE THREAD

**Issue by RedBaron2** [WormieCorp/Wormies-AU-Helpers#17]
`Get-RedirectedUrl "https://www.dropbox.com/download?build=48.4.58&plat=win&type=full"`
`Get-RedirectedUrl "https://electron.authy.com/download?channel=stable&arch=x64&platform=win32&version=latest&product=authy"`
both of these urls should return the same with spaces escaped to `%20`, and they don't right now
## Expected Behavior
If you're describing a bug, tell us what should happen
When using the powershell command
`[uri]::EscapeUriString($url)`
 in `Get-RedirectedUrl` helper
the result is
`https://clientupdates.dropboxstatic.com/dbx-releng/client/Dropbox%252048.4.58%2520Offline%2520Installer.exe`
when it should be
`https://clientupdates.dropboxstatic.com/dbx-releng/client/Dropbox%252048.4.58%20Offline%20Installer.exe`

## Current Behavior
If describing a bug, tell us what happens instead of the expected behavior
The current behavior results in a 403 forbidden error

## Possible Solution

The easiest fix is to PR the `Get-RedirectedUrl` helper to have a switch for EscapeUriString usage
PR submitted with automated check also with regex

## Steps to Reproduce (for bugs)

1. `Get-RedirectedUrl "https://www.dropbox.com/download?build=48.4.58&plat=win&type=full"`
2. `Get-RedirectedUrl "https://electron.authy.com/download?channel=stable&arch=x64&platform=win32&version=latest&product=authy"`

## Your Environment

* Package Version used: Latest
* Operating System and version: 10.0.17661.1001 build 1803
* Chocolatey version: N/A
* Install/uninstall gist: [Chocobot](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/455aeb6c215ea79d2a03a103649c5a35afaccef3)

**Comment by AdmiringWorm** [comment]
Just some clarification (and a reminder for myself) on what the issue actually is.

The URL from dropbox is already correctly escaped when we get it, as such the `%` symbol is escaped with (`%25`).
The `Get-RedirectedURL` helper should handle such scenarios, and not escape `%` symbols when followed by numbers (or perhaps unescape the url before escaping again, just in case).

**Comment by RedBaron2** [comment]
OK I have an idea that might solve the bug
I'll update the PR then

**Comment by AdmiringWorm** [comment]
hmm, just playing with a thought here and wanted your input.

Could perhaps add a check to see if the url matches the following `\%20` and in those cases we'll consider the url to be already escaped and skip the escaping of the url. Thoughts?

**Comment by AdmiringWorm** [comment]
I believe that would be the easiest right now, and could perhaps improve the check over time when needed.

**Comment by RedBaron2** [comment]
Yeah that would be the easiest too, 😄

**Comment by AdmiringWorm** [comment]
wait, I was a little quick. I actually meant `\%\d+`

**Comment by AdmiringWorm** [comment]
a new version was pushed to chocolatey now, I'll update the core team repo when it has been approved.
