### ISSUE TITLE
Allow users to add a whitelist to Expand-Aliases

### ISSUE THREAD

**Issue by AdmiringWorm** [WormieCorp/Wormies-AU-Helpers#18]
Would be useful to have the ability to add a white list of aliases that shouldn't be expanded when running `Expand-Aliases`.

**Comment by AdmiringWorm** [comment]
I have added this now in a local branch, and is ready to be published when the next release comes around.

/cc @majkinetor (I believe you were the one that asked for this feature some time ago?)

**Comment by majkinetor** [comment]
Removing % and ? from expanding on core ASAP.

**Comment by AdmiringWorm** [comment]
it's not available yet, and won't be either until the rest of my planned features have been implemented.

The issue was just closed since I pushed the code up to github.

**Comment by majkinetor** [comment]
I noticed.

I have it prepared: `if (Test-Path tools) { Expand-Aliases -Directory tools -Whitelist '?','%','ls' }` , just let me know when you push to gallery 👂

**Comment by AdmiringWorm** [comment]
While I agree adding the `?` and `%`, as that could potentially be mapped to a executable which could break the install script for those users.

You should also add the `Get-PackageParameter` to the whitelist, as that have been changed to an alias in chocolatey.

**Comment by majkinetor** [comment]
It can't AFAIK. Aliases have priority over exes and ls is there among internal aliases since v0. And furthemore, `Get-ChildItem` vs `ls` is really no brainer. Not everybody is in this non alias nonsence vagon: https://github.com/PowerShell/PSScriptAnalyzer/issues/214

**Comment by majkinetor** [comment]
Let me stand corrected. On linux it can and it does now. But when we arrive with chocolatey on Linux then we will think about that.
