### ISSUE TITLE
Procedure for the proper way to integrate Wormies-AU-Helpers

### ISSUE THREAD

**Issue by chtof** [WormieCorp/Wormies-AU-Helpers#28]
Hi,

Could you tell me where I can find a procedure regarding the proper way to integrate Wormies-AU-Helpers with AppVeyor or tell me how to do this?

Thanks in advance.

**Comment by AdmiringWorm** [comment]
First step is to just install the powershell module.
This can be done either through chocolatey (`choco install wormies-au-helpers`) or through the powershell gallery (`Install-Module -Name Wormies-AU-Helpers`).
The recommended way is through chocolatey.

After that, it should be made available and can be used immediately by just calling one of the provided functions.

In some cases, you may have to import the module yourself before it can be used (`Import-Module Wormies-AU-Helpers`).

**Comment by chtof** [comment]
Just tried but it doesn't work from appveyor. Maybe I have to adjust an environment variable or to install Wormies-AU-Helpers in a specific directory?

**Comment by AdmiringWorm** [comment]
Can you tell me the steps you're trying when installing and using the module?
Or link me to a repo if you have a public one?

I'm using this module myself in my chocolatey repo, as well as it's being used in the coreteampackages repo.

**Comment by chtof** [comment]
Here is the repo: https://github.com/chtof/chocolatey-packages/tree/master/automatic/stremio
update.ps1 runs perfectly from my computer.
I use "[Chocolatey Automatic Updater Module](https://github.com/majkinetor/au/blob/master/README.md)", and on AppVeyor, I have an account who launch regularly my "update.ps1" files. But for this one, it doesn't work as AppVeyor didn't find "Get-RedirectedUrl".

**Comment by AdmiringWorm** [comment]
From what I can see (looked at your `.appveyor.yml` file), you don't install the module anywhere.

In the `.appveyor.yml` file, after the line installing `AU` (Line 58), add another line with `- choco install wormies-au-helpers`.

This should then have your update script being able to make use of the `Get-Redirected` function.

**Comment by chtof** [comment]
It doesn't work. Your package depends on Powershell and seems the problem is with the installation of Powershell:

_ERROR: Windows Update Service is disabled - PowerShell updates are distributed as windows updates and so require the service. Consider temporarily enabling it before calling this package and disabling again afterward.
The install of powershell was NOT successful._

> Build started
> git config --global user.email "*****************************t"
> git config --global user.name "Chocolatey"
> git config --global core.safecrlf false
> git clone -q --branch=master https://github.com/chtof/chocolatey-packages.git C:\projects\chocolatey-packages
> git checkout -qf ********************************
> Running Install scripts
> Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version
> Caption        : Microsoft Windows Server 2012 R2 Datacenter
> OSArchitecture : 64-bit
> Version        : 6.3.9600
> $PSVersionTable
> Name                           Value                                                                                                                                                                                                 
> ----                           -----                                                                                                                                                                                                 
> PSVersion                      5.1.14409.1012                                                                                                                                                                                        
> PSEdition                      Desktop                                                                                                                                                                                               
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                               
> BuildVersion                   10.0.14409.1012                                                                                                                                                                                       
> CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
> WSManStackVersion              3.0                                                                                                                                                                                                   
> PSRemotingProtocolVersion      2.3                                                                                                                                                                                                   
> SerializationVersion           1.1.0.1                                                                                                                                                                                               
> git --version
> git version 2.17.1.windows.2
> git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
> . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version
> choco install wormies-au-helpers
> Build parameters:
>   Install              True
>   Version              2018.5.18
>   NoChocoPackage       True
> ==| Building AU 2018.5.18
> Removing older builds
> Creating module manifest
> Creating module help
> Creating 7z package
> Skipping chocolatey package build
> ==| Starting AU installation
> Module path: 'C:\Users\appveyor\AppData\Local\Temp\1\au\_build\2018.5.18\AU'
> AU version 2018.5.18 installed successfully at 'C:\Program Files\WindowsPowerShell\Modules\AU'
>   Function             Alias
>   --------             -----
>   Get-AUPackages       gau lsau
>   Get-RemoteChecksum   
>   Get-RemoteFiles      
>   Get-Version          
>   Push-Package         
>   Set-DescriptionFromReadme 
>   Test-Package         
>   Update-AUPackages    updateall
>   Update-Package       update
> To learn more about AU:      man about_AU
> See help for any function:   man updateall
> 2018.5.18
> Chocolatey v0.10.11
> Installing the following packages:
> wormies-au-helpers
> By installing you accept licenses for the packages.
> Progress: Downloading PowerShell 5.1.14409.20180811... 5%
> Progress: Downloading PowerShell 5.1.14409.20180811... 17%
> Progress: Downloading PowerShell 5.1.14409.20180811... 29%
> Progress: Downloading PowerShell 5.1.14409.20180811... 41%
> Progress: Downloading PowerShell 5.1.14409.20180811... 53%
> Progress: Downloading PowerShell 5.1.14409.20180811... 65%
> Progress: Downloading PowerShell 5.1.14409.20180811... 77%
> Progress: Downloading PowerShell 5.1.14409.20180811... 89%
> Progress: Downloading PowerShell 5.1.14409.20180811... 100%
> Progress: Downloading wormies-au-helpers 0.3.2... 2%
> Progress: Downloading wormies-au-helpers 0.3.2... 8%
> Progress: Downloading wormies-au-helpers 0.3.2... 13%
> Progress: Downloading wormies-au-helpers 0.3.2... 19%
> Progress: Downloading wormies-au-helpers 0.3.2... 25%
> Progress: Downloading wormies-au-helpers 0.3.2... 30%
> Progress: Downloading wormies-au-helpers 0.3.2... 36%
> Progress: Downloading wormies-au-helpers 0.3.2... 41%
> Progress: Downloading wormies-au-helpers 0.3.2... 47%
> Progress: Downloading wormies-au-helpers 0.3.2... 53%
> Progress: Downloading wormies-au-helpers 0.3.2... 58%
> Progress: Downloading wormies-au-helpers 0.3.2... 64%
> Progress: Downloading wormies-au-helpers 0.3.2... 69%
> Progress: Downloading wormies-au-helpers 0.3.2... 75%
> Progress: Downloading wormies-au-helpers 0.3.2... 81%
> Progress: Downloading wormies-au-helpers 0.3.2... 86%
> Progress: Downloading wormies-au-helpers 0.3.2... 92%
> Progress: Downloading wormies-au-helpers 0.3.2... 97%
> Progress: Downloading wormies-au-helpers 0.3.2... 100%
> PowerShell v5.1.14409.20180811 [Approved]
> powershell package files install completed. Performing other installation steps.
> Running on: Windows Server 2012 R2 Datacenter, (ServerDatacenter), Windows Kernel: 6.3.9600
> ERROR: Windows Update Service is disabled - PowerShell updates are distributed as windows updates and so require the service.  Consider temporarily enabling it before calling this package and disabling again afterward.
> The install of powershell was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\PowerShell\tools\ChocolateyInstall.ps1'.
>  See log for details.
> wormies-au-helpers v0.3.2 [Approved]
> wormies-au-helpers package files install completed. Performing other installation steps.
> Extracting C:\ProgramData\chocolatey\lib\wormies-au-helpers\tools/Wormies-AU-Helpers.7z to C:\Users\appveyor\AppData\Local\Temp\1\chocolatey/Wormies-AU-Helpers...
> C:\Users\appveyor\AppData\Local\Temp\1\chocolatey/Wormies-AU-Helpers
> ==| Starting Wormies-AU-Helpers installation
> Module path: 'C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\Wormies-AU-Helpers\Wormies-AU-Helpers'
> Wormies-AU-Helpers version 0.3.2 installed successfully at 'C:\Program Files\WindowsPowerShell\Modules\Wormies-AU-Helpers
>   Function             Alias
>   --------             -----
>   Expand-Aliases       
>   Get-FixVersion       
>   Get-RedirectedUrl    
>   Update-Metadata      
> To learn more about Wormies-AU-Helpers:    man about_Wormies-AU-Helpers
> See help for any function:    man updateall
>  The install of wormies-au-helpers was successful.
>   Software installed to 'C:\Users\appveyor\AppData\Local\Temp\1\chocolatey/Wormies-AU-Helpers'
> Chocolatey installed 1/2 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> **Failures
>  - powershell (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\PowerShell\tools\ChocolateyInstall.ps1'.
>  See log for details.
> Command exited with code -1**

**Comment by AdmiringWorm** [comment]
Completely forgot about that. In that case you have several options available.

- Enable the Windows Update Service, then install the package
- Register the powershell package (`choco install powershell -n`), then install the wormies-au-helper package.
- Ignore the dependency on the package `choco install wormies-au-helpers --ignore-dependencies`.

I see that I'm using the last option myself, but the second option is also good if you expect to install several packages in the future that depends on powershell.

**Comment by chtof** [comment]
I have choose the second option and it works!

A great thank for your help!
And also, have a nice week-end.

So, can be **closed**.

**Comment by AdmiringWorm** [comment]
Great that you got it to work.

If you got any further questions regarding the module, please feel free to jump into the gitter channel to ask them there (https://gitter.im/WormieCorp/Wormies-AU-Helpers)
